### PR TITLE
Update PDF.js to v2.11.249

### PR DESCRIPTION
**Pull request by robertknight**
Update PDF.js to the latest release. See the corresponding [browser-extension PR](https://github.com/hypothesis/browser-extension/pull/631) for information on the changes this includes. 

This is mostly a result of running `make update-pdfjs`, but a minor change to our pdfjs-init.js script was required. See first commit for details.

_Update: I also changed the `bin/update-pdfjs` script so that it downloads the _legacy_ build of PDF.js which has [browser support](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#which-browsers-are-supported) that closely matches the client (Safari 11+, Chrome 68+ etc.)._

When testing this branch, you will need to run `make build` to regenerate static assets. The version of PDF.js in use is reported in browser devtools. Additionally make sure you have an up to date client, as several [client changes](https://github.com/hypothesis/client/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Project%3A+PDF.js+upgrade%22) were needed to support this release.

### CODE REVIEW

**Comment by robertknight** [comment]
I'm planning to let the new PDF.js release "bake" in the browser extension for a few days before we ship it to LMS users in Via. I'd like to get it reviewed soon so that it is ready to go however.

**Review by esanzgar — APPROVED** [review]
👍🏼

**Comment by robertknight** [comment]
Something I overlooked last week was re-checking browser support. PDF.js comes in [two flavors](https://github.com/mozilla/pdf.js#online-demo), a modern version and one that supports older browsers. The PDF.js repo has links to the demo built using the [modern version](https://mozilla.github.io/pdf.js/web/viewer.html) and the [legacy version](https://mozilla.github.io/pdf.js/legacy/web/viewer.html).

Testing with the demo app, it looks like the modern version currently requires:

Chrome >= 85, Firefox >= 79, Edge >= 85, Safari >= 14.

The Chrome and Safari requirements are definitely an issue for use in Via.

The versions of PDF.js supported by the _legacy_ build are described [in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support). They align pretty closely with the recently proposed [browser baseline for the client](https://github.com/hypothesis/client/issues/3744).

**Comment by robertknight** [comment]
I have revised this PR to use the legacy rather than modern build of PDF.js, mostly for compatibility with Safari 11-13 and Chrome 70-84, since we still see a total of ~3.5% of users on those builds (mostly older Safari).

The `bin/update-pdfjs` script has [been updated](https://github.com/hypothesis/via/commit/9e3b832b327a37c198cb278bc97ad928578b2094) to download the legacy build and the PDF.js update commit has been [recreated](https://github.com/hypothesis/via/commit/23a7a99eb8983b5dbbb67cd8747dde4653184420) using it. This bumps the PDF.js version slightly from 2.11.113 to 2.11.249.

**Pull request merged**
