### PR TITLE
Serve PDFs by rendering the PDF.js viewer directly

### PR DESCRIPTION
**Pull request by nickstenning**
Rather than redirecting the user to some ugly URL,

    /static/__shared/viewer/web/viewer.html?file=http://...

this commit renders the PDF.js viewer directly when it detects that the file it is going to serve is a PDF.

As a bonus, this allows us to inject a <link rel="canonical"> tag into the PDF.js viewer HTML, for consistency with other pages rewritten by via.

### CODE REVIEW

**Comment by nickstenning** [comment]
- [ ] We should add a redirect for old-style URLs

**Comment by ikreymer** [comment]
That's awesome! Will try to test out on my heroku instance just in case, but looks great.

For old-style urls, probably easiest to replace the `viewer.html` with a stub that redirects to proper url in JS.

**Comment by ikreymer** [comment]
- [X] We should add a redirect for old-style URLs

Added the redirect, lmk if this looks good (or if there are other cases, I think this should cover it as they should all be under `/static/__shared/viewer/web/viewer.html` currently.

**Comment by nickstenning** [comment]
Yo @ikreymer! As I mentioned in my email I've rejigged this a bit so we don't need to do the redirect client-side. Let me know if you see any problems with this approach. If not, we can merge this and get it deployed.

**Comment by ikreymer** [comment]
Looks good! Feel free to merge and deploy!

**Pull request merged**
