### PR TITLE
update to pywb 0.10.5

### PR DESCRIPTION
**Pull request by ikreymer**
A new pywb is ready.. this has some more rewriting improvements, most notably for sites that use postMessage().. Pages with Disqus comments should now work.

### CODE REVIEW

**Comment by ikreymer** [comment]
Also, cookies will now default to the host scope instead of root, avoiding the main issue of cookie leakage/too many cookies.. 

If a cookie has `Domain=.example.com`, it will just get converted to `Path=/example.com/` before it was `Path=/`

**Comment by tilgovi** [comment]
Wow. That's interesting.

**Comment by tilgovi** [comment]
That's clever. So, if the cookies all have paths prepended, they should work and sites shouln't be able to access one another's cookies, yeah?

**Comment by ikreymer** [comment]
Yep. The downside is that it could break sites where `http://via.hypothes.is/subdomain.example.com` depends on a `Domain=.example.com` cookie set on `http://via.hypothes.is/example.com`
In practice, this doesn't seem to be very common, unless users are logging in, and that's not the main use case for via anyway.

I guess we can see if this causes issues to any non-login sites.

**Comment by tilgovi** [comment]
:+1: it's rolling out to production right now. Thanks, @ikreymer!

**Pull request merged**
