### PR TITLE
Update pywb dependency

### LINKED ISSUE #69: Via fails for GamesandLearning wordpress blog
https://via.hypothes.is/https://gamesandlearning.wordpress.com/2016/02/19/playful-annotation-in-the-open/

Fails:

GET https://via.hypothes.is/https://gamesandlearning.wordpress.com/2016/02/19/playful-annotation-in-the-open/%7B%7Bobj._user.profile_image%7D%7D 404 (OK)

### PR DESCRIPTION
**Pull request by chdorner**
The fix for #69 resulted in a change inside the pywb source code. I've opened a pull request at https://github.com/ikreymer/pywb/pull/183 - in the meantime this changes the dependency to use my fork with that one commit. Also note that this will update the pywb version to 0.30.1. I did some testing locally and everything seems to be working. My plan is when this and #74 are merged to set up a staging environment (which would be a nice to have anyway) and then do more testing before this should go out to production.

Fixes #69.

### CODE REVIEW

**Comment by nickstenning** [comment]
Rather than every member of the team maintaining their own fork of pywb, could we fork it to the hypothesis organisation?

**Comment by chdorner** [comment]
Sure, but I guess the goal is to have this in pywb upstream anyway. Roberts changes were merged and released just some days after he fixed them, we just never bothered to change the pywb dependency back to the original (see #67).
I can still fork it to the hypothesis org and then add the changes there.

**Comment by nickstenning** [comment]
Being an upstream dependency, I'd guess we're going to have this pattern (fork until upstream is updated) frequently, and then at some point we're going to be in a position where we want hotfixes from more than one team member, and then having our own fork would seem easier to manage than cherry-picking commits between different people's repositories.

**Comment by nickstenning** [comment]
LGTM.

**Comment by ikreymer** [comment]
Is there anything I can do to make this easier? I try to do point releases whenever possible, but of course not always possible to keep up with your timetable. I can probably release this pretty soon though as its just a small fix.

For me, I guess if you also updated the changelist and bumped the version in the pull request, that would make it even easier to merge and release quickly. Thank you for submitting the pull request though, I definitely appreciate the fix!

**Comment by nickstenning** [comment]
@ikreymer Nope! My comment was in no way intended as a criticism. Indeed, compared to many upstream projects we depend on you're positively perfect in your responsiveness :)

Regardless, there will be times when we need to get a fix out pronto and we'll use our fork for those situations.

**Comment by nickstenning** [comment]
Oh, and we'll make a note to update CHANGES and bump the version next time we submit things upstream.

**Pull request merged**
