### PR TITLE
Address https://github.com/hypothesis/via/issues/18

### PR DESCRIPTION
**Pull request by judell**

### CODE REVIEW

**Comment by BigBlueHat** [comment]
@tilgovi @ikreymer could one of you give this a quick test?

I'm getting weird `pip install` errors at the moment...

The code looks fine, but I'd like someone to see it work before clicking "merge." :smile:

**Comment by tilgovi** [comment]
Please don't merge this until someone can at least explain why this is necessary, given that the same code is in templates/banner.html. I'm guessing that it's because the PDF viewer.html isn't rewritten? Could it still have the banner injected?

**Comment by judell** [comment]
> Could it still have the banner injected?

That sounds promising. @BigBlueHat?

**Comment by BigBlueHat** [comment]
Looks like it used to have a head_insert template:
https://github.com/hypothesis/via/commit/cff52b232a96b3918a908ab4a37e353568d4bb56#diff-259fe82e12a866f01123927480c7851bL12

@ikreymer is that still a supported option for the PDF viewer? We'd like it to share the same banner.html inject...or have it's own if need be.

**Comment by ikreymer** [comment]
Yes, the viewer.js is under `/static/` so it is served as it is.. Essentially the pdf handling works by redirecting to the static pdf viewer, which could just be part of static assets somewhere and doesn't even need to be part of via. Currently, the pdf viewer is basically completely separate from the rest of via.

However, I do remember that we discussed changing this so that the viewer is served directly without the redirect. Does that still make sense? I think that would mean that loading 'somefile.pdf' would actually load an html page (viewer.html) which would then load the actual pdf. That would probably mean more changes to the pdf.js for that to work.

**Comment by ikreymer** [comment]
But for purposes of this pull request, I think this looks fine and should work. I tested it with http://project.hypothes.is/design/margins/PageMargins.pdf and the highlights were showing up on load.

The change here should not affect `pip install` in any way so if there are errors that is some other issue.

**Comment by BigBlueHat** [comment]
Awesome. I'll report the pip thing separately. It's definitely unrelated...
it was just in my way for testing at the time. :-P

Thanks, Ilya!

@tilgovi @judell merge at your preference.

**Pull request merged**
