### PR TITLE
update to pywb 0.10.9

### LINKED ISSUE #34: Astrophysics Data System search page isn't annotate-able
https://via.hypothes.is/https://ui.adsabs.harvard.edu

Too much JS; not enough Web.

### PR DESCRIPTION
**Pull request by ikreymer**
Update to use 0.10.9, should fix #34 and address #50 at least

### CODE REVIEW

**Comment by BigBlueHat** [comment]
@nickstenning @judell what's the best way to get this in our :shipit: queue?

**Comment by tilgovi** [comment]
@BigBlueHat hit the merge button

**Comment by BigBlueHat** [comment]
...the big green one?! :wink:

**Comment by BigBlueHat** [comment]
Thanks @ikreymer!

**Comment by ikreymer** [comment]
It doesn't look like its been pushed to `via.hypothes.is` yet.., assume someone has to do it manually..

**Pull request merged**
